#ifndef	_PLANE_ERROR_STATES_
#define _PLANE_ERROR_STATES_

typedef enum{
	PLANE_STATUS_CHANGED,
	PLANE_CREATED,
	PLANE_CREATION_ERROR,
	PLANE_LAND_ERROR,
	PLANE_TAKEOFF_ERROR,
	TIME_SET,
	TIME_NOT_SET,
	NO_NEED,
	PLANE_IDLE_WAY
}PlaneError_t;

#endif
