#ifndef	_CICULAR_LIST_ERROR_
#define _CICULAR_LIST_ERROR_

typedef enum clist_error{
	LIST_CREATED,
	LIST_DESTROYED,
	LIST_EMPTY,
	LIST_NOT_EMPTY,
	LIST_NOT_FULL,
	LIST_FULL,
	HEAD_REVIELED,
	INSERTION_SUCCESS,
	FIRST_TIME_INSERTION,
	DELETION_DONE,
	LIST_RETRIEVED,
	LIST_REPLACED,
	LIST_TRAVERSED,
	NULL_POINTER,
}CListError_t;

#endif