#ifndef _ADT_ERROR_STATES_
#define _ADT_ERROR_STATES_

typedef enum{
	STACK_CREATED,
	CREATION_ERROR,
	STACK_CLEARED,
	STACK_EMPTY,
	STACK_NOT_EMPTY,
	STACK_FULL,
	STACK_NOT_FULL,
	TOP_ELEMENT_REVEILED,
	PUSHED_SUCCESSFULLY,
	POPPED_SUCCESSFULLY
}ErrorStates_t;

#endif