#ifndef	_DOUBLY_LIST_ERROR_
#define _DOUBLY_LIST_ERROR_

typedef enum dlisterror{
	LIST_CREATED,
	LIST_DESTROYED,
	LIST_EMPTY,
	LIST_NOT_EMPTY,
	LIST_NOT_FULL,
	LIST_FULL,
	HEAD_REVIELED,
	INSERTION_SUCCESS,
	FIRST_TIME_INSERTION,
	DELETION_DONE,
	LIST_RETRIEVED,
	LIST_REPLACED,
	LIST_TRAVERSED,
	NULL_POINTER,
}DListError_t;

#endif