#ifndef	_APP_ERROR_
#define _APP_ERROR_

typedef enum AppError{
	APP_INITIALIZED,
	PLANE_LAUNCHED,
	PLANE_ON_RUN_WAY,
	PLANE_TAKEOFF_DELAYED,
	PLANE_LAND_DELAYED,
	PLANE_REQUEST_LANDING,
	NOW_FLIGHTS_NOW,
	PLANE_LANDED,
	PLANE_FLYED,
	RUNWAY_CHECKED,
	ON_AIR_CHECKED,
	AIRPORT_CHECKED,
}AppError_t;

#endif