#ifndef	_ADT_LIST_ERROR_STATES_
#define _ADT_LIST_ERROR_STATES_

typedef enum{
	LIST_CREATED,
	LIST_DESTROYED,
	LIST_EMPTY,
	LIST_NOT_EMPTY,
	LIST_FULL,
	LIST_NOT_FULL,
	LIST_INSERTION_DONE,
	LIST_DELETION_DONE,
	LIST_RETRIVE_DONE,
	LIST_REPLACEMENT_DONE,
	LIST_TRAVERSED,
	LIST_NULL_POINTER
}ListErrorStates_t;

#endif