#ifndef _ADT_QUEUE_ES_
#define _ADT_QUEUE_ES_

typedef enum{
	QUEUE_CREATED,
	QUEUE_CLEARED,
	QUEUE_EMPTY,
	QUEUE_NOT_EMPTY,
	QUEUE_FULL,
	QUEUE_NOT_FULL,
	QUEUE_FRONT_REVEILED,
	QUEUE_REAR_REVEILED,
	QUEUE_TRAVERSED,
	QUEUE_PUSHED_SUCCESSFULLY,
	QUEUE_POPPED_SUCCESSFULLY,
	NULL_POINTER
}ErrorStates_t;

#endif